name: Auto Merge Main to Other Branches

on:
  push:
    branches:
      - main
  workflow_dispatch: # 手动触发

jobs:
  merge-to-base:
    name: Merge main into base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_AUTO_MERGE }}

      - name: Merge main into base
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout base
          git merge main --no-ff -m "Auto merge main into base"
          git push origin base

  merge-to-base-login:
    name: Merge main into base-login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_AUTO_MERGE }}

      - name: Merge main into base-login
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout base-login
          git merge main --no-ff -m "Auto merge main into base-login"
          git push origin base-login

  merge-to-base-i18n:
    name: Merge main into base-i18n
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_AUTO_MERGE }}

      - name: Merge main into base-i18n
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout base-i18n
          git merge main --no-ff -m "Auto merge main into base-i18n"
          git push origin base-i18n

  merge-to-base-i18n-login:
    name: Merge main into base-i18n-login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN_AUTO_MERGE }}

      - name: Merge main into base-i18n-login
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout base-i18n-login
          git merge main --no-ff -m "Auto merge main into base-i18n-login"
          git push origin base-i18n-login
